name: CD

env:
  LOAD_TESTING_NAME: 'lt-core'
  LOAD_TESTING_SCRIPT: './JMeterScripts/test.yaml'
  AZURE_WEBAPP_PACKAGE_PATH: './simpleloadtesting'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
            ProjectName:
              description: 'projectName'     
              required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}     
      
      - name: Restore
        run: dotnet restore "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Build 
        run: dotnet build "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" --configuration Release
      - name: dotnet publish
        run: dotnet publish "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{github.event.inputs.ProjectName }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      
      - name: Deploying iac
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LOADTEST_AZURE_CREDENTIALS }}
  test:  
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Load Testing
        uses: Azure/load-testing@v1
        with:
          # Path of the YAML file. Should be fully qualified path or relative to the default working directory
          loadtestConfigFile: ${{ env.LOAD_TESTING_SCRIPT }}
          # Enter or Select the name of an existing Azure Load Testing resource
          loadtestResource: ${{ env.LOAD_TESTING_NAME }}
          # Enter or Select the Azure Resource Group that contains the Load test resource specified above
          resourceGroup: 'rg-demos'         
