# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
    workflow_dispatch:
        inputs:
                ProjectName:
                  description: 'projectName'     
                  required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-iac:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - name: Checkout iac
       uses: actions/checkout@v3.0.0
       with:
         # Repository name with owner. For example, actions/checkout
         repository: bpfoster85/learn.iac-bicep-modules
         path: ./iacrepo
         
     - name: Deploying iac
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

     - name: deploy
       uses: azure/arm-deploy@v1
       with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./iacrepo/Main_Deployments/FullAppServiceDeployment.bicep
        parameters: planName=${{github.event.inputs.ProjectName }} location=${{ secrets.AZURE_RG }}
        failOnStdErr: false  

        
